In [1]:
import numpy as np
import pandas as pd
from trackml.dataset import load_event, load_dataset


## To-Do:

1. 5 FC layers, 4k-2k-2k-2k-1k


Generate Training Data:
-For all hits in all tracks
    -construct all pairs of 

In [7]:
def get_event(num):
    train_dir = '../data/train_sample/'
    hits, cells, particles, truth = load_event(train_dir+'event00000'+str(num))
    return hits, cells, particles, truth


In [8]:
hits, cells, particles, truth = get_event(1000)

In [25]:
hit_cell_count = cells.groupby(['hit_id']).value.count().values
hit_value_sum = cells.groupby(['hit_id']).value.sum().values
#not sure above 2 features are useful
features = np.hstack((hits[['x','y','z']]/1000, hit_cell_count.reshape(len(hit_cell_count),1)/10,hit_value_sum.reshape(len(hit_value_sum),1)))

In [38]:
particle_ids = truth.particle_id.unique()

In [39]:
particle_ids

array([                 0,  22525763437723648, 297237712845406208, ...,
       734104812500557826, 878208593143271425, 860199142452891649])

In [40]:
test = particle_ids[np.where(particle_ids!=0)]

In [53]:
aParticle = test[0]

In [56]:
hit_ids = truth[truth.particle_id==aParticle].hit_id.values

In [58]:
hit_ids

array([   2, 1420, 1460, 3170, 3234, 5343, 5424, 5482, 7867, 7951],
      dtype=int32)

In [59]:
hit_ids2 = truth[truth.particle_id==aParticle].hit_id.values-1

In [60]:

hit_ids2

array([   1, 1419, 1459, 3169, 3233, 5342, 5423, 5481, 7866, 7950],
      dtype=int32)

In [62]:
truth.head()

hit_id         particle_id         tx        ty      tz            tpx  \
0       1                   0 -64.411598 -7.164120 -1502.5  250710.000000   
1       2   22525763437723648 -55.338501  0.630805 -1502.5      -0.570605   
2       3                   0 -83.828003 -1.145580 -1502.5  626295.000000   
3       4  297237712845406208 -96.122902 -8.230360 -1502.5      -0.225235   
4       5  418835796137607168 -62.659401 -9.375040 -1502.5      -0.281806   

             tpy           tpz    weight  
0 -149908.000000 -956385.00000  0.000000  
1       0.028390     -15.49220  0.000010  
2 -169767.000000 -760877.00000  0.000000  
3      -0.050968      -3.70232  0.000008  
4      -0.023487      -6.57318  0.000009